-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH 
from MEMBER_PROFILE as m
where GENDER LIKE 'W' and DATE_FORMAT(DATE_OF_BIRTH, '%m') LIKE '03' and TLNO IS NOT NULL
Order by MEMBER_ID ASC